services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: smarttrainer_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - smarttrainer_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: smarttrainer_web
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - smarttrainer_net

networks:
  smarttrainer_net:
    driver: bridge
